name: Fork & Edit 
on:
  workflow_dispatch:
  schedule:
    - cron: "* */12 * * *"
  
jobs:
  Fork-FLITER-list:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'
    
    steps: 
    - name: Checkout target Repository
      uses: actions/checkout@v4.1.0
      with:
        Repository: ffddh/Tool
        path: Tool-repo

######

      # Fork Chxm1023 重写规则
    - name: Fork Chxm1023 Rewrite
      run: |
        mkdir -p Tool-repo/Repository/chxm1023/Rewrite
        git clone -b main https://github.com/chxm1023/Rewrite.git  czy_Tmp
        cp -r czy_Tmp/* Tool-repo/Repository/chxm1023/Rewrite
        rm -rf czy_Tmp 
      # 修改脚本链接
    - name: Edit Chxm1023/Rewrite
      run: |
        cd Tool-repo/Repository/chxm1023/Rewrite
        for file in *.js; do
            if [ "$file" ] ; then
              # 修改脚本链接
              sed -i 's/raw\.githubusercontent\.com\/chxm1023\/Rewrite\/main/raw.githubusercontent\.com\/ffddh\/Tool\/main\/Repository\/chxm1023\/Rewrite/g' "$file"
            else
              echo "$file not found."
            fi
          done
      # 修改脚本链接
    - name: Edit Rewrite/Revenuecat
      run: |
        cd Tool-repo/Repository/chxm1023/Rewrite/Revenuecat
        for file in *.js; do
            if [ "$file" ] ; then
              # 修改脚本链接
              sed -i 's/raw\.githubusercontent\.com\/chxm1023\/Rewrite\/main\/Revenuecat/raw.githubusercontent\.com\/ffddh\/Tool\/main\/Repository\/chxm1023\/Rewrite\/Revenuecat/g' "$file"
            else
              echo "$file not found."
            fi
          done
      # 修改脚本链接
    - name: Edit Rewrite/iTunes
      run: |
        cd Tool-repo/Repository/chxm1023/Rewrite/iTunes
        for file in *.js; do
            if [ "$file" ] ; then
              # 修改脚本链接
              sed -i 's/raw\.githubusercontent\.com\/chxm1023\/Rewrite\/main\/iTunes/raw.githubusercontent\.com\/ffddh\/Tool\/main\/Repository\/chxm1023\/Rewrite\/iTunes/g' "$file"
            else
              echo "$file not found."
            fi
          done

      # Fork Chxm1023 去广告规则
    - name: Fork Chxm1023 Advertising
      run: |
        mkdir -p Tool-repo/Repository/chxm1023/Advertising
        git clone -b main https://github.com/chxm1023/Advertising.git  cyz_Tmp
        cp -r cyz_Tmp/* Tool-repo/Repository/chxm1023/Advertising
        rm -rf cyz_Tmp
      # 修改脚本链接
    - name: Edit Advertising
      run: |
        cd Tool-repo/Repository/chxm1023/Advertising
        for file in *.js; do
            if [ "$file" ] ; then
              # 修改脚本链接
              sed -i 's/raw\.githubusercontent\.com\/chxm1023\/Advertising\/main/raw.githubusercontent\.com\/ffddh\/Tool\/main\/Repository\/chxm1023\/Advertising/g' "$file"
            else
              echo "$file not found."
            fi
          done

      # Fork Chxm1023 重写合集
    - name: Fork Chxm1023 Script_X
      run: |
        mkdir -p Tool-repo/Repository/chxm1023/Script_X
        git clone -b main https://github.com/chxm1023/Script_X.git  yzc_Tmp
        cp -r yzc_Tmp/* Tool-repo/Repository/chxm1023/Script_X
        rm -rf yzc_Tmp   

      # Fork RuCu6 分流规则&重写规则
    - name: Fork RuCu6 Rules
      run: |
        mkdir -p Tool-repo/Repository/RuCu6
        git clone -b main https://github.com/RuCu6/QuanX.git  qwe_Tmp
        cp -r qwe_Tmp/* Tool-repo/Repository/RuCu6
        rm -rf qwe_Tmp

      # Fork yqc007 重写脚本
    - name: Fork yqc007 Rewrite
      run: |
        mkdir -p Tool-repo/Repository/yqc007
        git clone -b master https://github.com/yqc007/QuantumultX.git  ewq_Tmp
        cp -r ewq_Tmp/* Tool-repo/Repository/yqc007
        rm -rf ewq_Tmp
      # 修改脚本链接
    - name: Edit QuantumultX/yqc007
      run: |
        cd Tool-repo/Repository/yqc007
        for file in *.js; do
            if [ "$file" ] ; then
              # 修改脚本链接
              sed -i 's/raw\.githubusercontent\.com\/yqc007\/QuantumultX\/master/raw.githubusercontent\.com\/ffddh\/Tool\/main\/Repository\/yqc007/g' "$file"
            else
              echo "$file not found."
            fi
          done

      # Fork 可莉插件、脚本
    - name: Fork lodepuly Plugin&Script
      run: |
        mkdir -p Tool-repo/Repository/KeLee
        git clone https://gitlab.com/lodepuly/vpn_tool.git lodepuly_Tmp
        cp -r lodepuly_Tmp/* Tool-repo/Repository/KeLee
        rm -rf lodepuly_Tmp
      # 修改脚本链接
    - name: Edit KeLee/QuantumultX
      run: |
        cd Tool-repo/Repository/KeLee/Tool/QuantumultX/Rewrite
        for file in *.snippet; do
            if [ "$file" ] ; then
              # 修改脚本链接
              sed -i 's/gitlab\.com\/lodepuly\/vpn_tool\/-\/raw\/master\/Resource\/Script/raw.githubusercontent\.com\/ffddh\/Tool\/main\/Repository\/KeLee\/Resource\/Script/g' "$file"
            else
              echo "$file not found."
            fi
          done
      # 修改脚本链接
    - name: Edit KeLee/Loon
      run: |
        cd Tool-repo/Repository/KeLee/Tool/Loon/Plugin
        for file in *.plugin; do
            if [ "$file" ] ; then
              # 修改脚本链接
              sed -i 's/gitlab\.com\/lodepuly\/vpn_tool\/-\/raw\/master\/Resource\/Script/raw.githubusercontent\.com\/ffddh\/Tool\/main\/Repository\/KeLee\/Resource\/Script/g' "$file"
            else
              echo "$file not found."
            fi
          done

      # Fork Peng-YM 定时任务&重写规则
    - name: Fork  Peng-YM Tasks&Rewrite
      run: |
        mkdir -p Tool-repo/Repository/Peng-YM
        git clone https://github.com/Peng-YM/QuanX.git asdf_Tmp
        cp -r asdf_Tmp/* Tool-repo/Repository/Peng-YM
        rm -rf asdf_Tmp

      # Fork NobyDa 脚本
    - name: Fork NobyDa Script
      run: |
        mkdir -p Tool-repo/Repository/NobyDa
        git clone -b master https://github.com/NobyDa/Script.git qaz_Tmp
        cp -r qaz_Tmp/* Tool-repo/Repository/NobyDa
        rm -rf qaz_Tmp

      # Fork Guding88 重写规则
    - name: Fork Guding88 Rewrite
      run: |
        mkdir -p Tool-repo/Repository/Guding88/Script
        git clone https://github.com/Guding88/Script.git qas_Tmp
        cp -r qas_Tmp/* Tool-repo/Repository/Guding88/Script
        rm -rf qas_Tmp
      # 修改脚本链接
    - name: Edit Guding88/Script
      run: |
        cd Tool-repo/Repository/Guding88/Script
        for file in *.js; do
            if [ "$file" ] ; then
              # 修改脚本链接
              sed -i 's/raw\.githubusercontent\.com\/Guding88\/Script\/main/raw.githubusercontent\.com\/ffddh\/Tool\/main\/Repository\/Guding88\/Script/g' "$file"
            else
              echo "$file not found."
            fi
          done
          
      # Fork fmz200 脚本&去广告规则
    - name: Fork fmz200 Script&Noads
      run: |
        mkdir -p Tool-repo/Repository/wool_scripts
        git clone https://github.com/fmz200/wool_scripts.git asf_Tmp
        cp -r asf_Tmp/* Tool-repo/Repository/wool_scripts
        rm -rf asf_Tmp
        
      # Fork zqzess 定时任务&分流规则
    - name: Fork zqzess Task&Filter
      run: |
        mkdir -p Tool-repo/Repository/zqzess
        git clone -b master https://github.com/zqzess/rule_for_quantumultX.git sfa_Tmp
        cp -r sfa_Tmp/* Tool-repo/Repository/zqzess
        rm -rf sfa_Tmp 

      # Fork ACL4SSR 去广告规则
    - name: Fork ACL4SSR Advertising
      run: |
        mkdir -p Tool-repo/Repository/ACL4SSR
        git clone -b master https://github.com/ACL4SSR/ACL4SSR.git sdf_Tmp
        cp -r sdf_Tmp/* Tool-repo/Repository/ACL4SSR
        rm -rf sdf_Tmp

      # Fork VirgilClyne iRingo苹果服务
    - name: Fork VirgilClyne iRingo
      run: |
        mkdir -p Tool-repo/Repository/VirgilClyne
        git clone -b main https://github.com/VirgilClyne/iRingo.git sty_Tmp
        cp -r sty_Tmp/* Tool-repo/Repository/VirgilClyne
        rm -rf sty_Tmp
      # Fork VirgilClyne iRingo wiki
    - name: Fork VirgilClyne Wiki
      run: |
        mkdir -p Tool-repo/Repository/VirgilClyne/WiKi
        git clone https://github.com/VirgilClyne/iRingo.wiki.git syt_Tmp
        cp -r syt_Tmp/* Tool-repo/Repository/VirgilClyne/WiKi
        rm -rf syt_Tmp

      # Fork BiliUniverse B站服务增强
      # 自动识别番剧影视地区并自动分流，自定义搜索各地区结果
    - name: Fork BiliUniverse Global
      run: |
        mkdir -p Tool-repo/Repository/BiliUniverse/Global
        git clone -b main https://github.com/BiliUniverse/Global.git yhn_Tmp
        cp -r yhn_Tmp/* Tool-repo/Repository/BiliUniverse/Global
        rm -rf yhn_Tmp
     # 哔哩哔哩流媒体平台功能增强系列模块
    - name: Fork BiliUniverse Universe
      run: |
        mkdir -p Tool-repo/Repository/BiliUniverse/Universe
        git clone -b main https://github.com/BiliUniverse/Universe.git ynh_Tmp
        cp -r ynh_Tmp/* Tool-repo/Repository/BiliUniverse/Universe
        rm -rf ynh_Tmp
     # 全面自定义哔哩哔哩app主界面
    - name: Fork BiliUniverse Enhanced
      run: |
        mkdir -p Tool-repo/Repository/BiliUniverse/Enhanced
        git clone -b main https://github.com/BiliUniverse/Enhanced.git hny_Tmp
        cp -r hny_Tmp/* Tool-repo/Repository/BiliUniverse/Enhanced
        rm -rf hny_Tmp
     # 通过公共解析服务器实现地区漫游，进而提供其他增强功能
    - name: Fork BiliUniverse Roaming
      run: |
        mkdir -p Tool-repo/Repository/BiliUniverse/Roaming
        git clone -b main https://github.com/BiliUniverse/Roaming.git hyn_Tmp
        cp -r hyn_Tmp/* Tool-repo/Repository/BiliUniverse/Roaming
        rm -rf hyn_Tmp
      # 🪐 BiliUniverse: 🧰 BoxJs
    - name: Fork BiliUniverse BoxJs
      run: |
        mkdir -p Tool-repo/Repository/BiliUniverse/BoxJs
        git clone -b main https://github.com/BiliUniverse/BoxJs.git nyh_Tmp
        cp -r nyh_Tmp/* Tool-repo/Repository/BiliUniverse/BoxJs
        rm -rf nyh_Tmp
      # 哔哩哔哩app去广告
    - name: Fork BiliUniverse ADBlock
      run: |
        mkdir -p Tool-repo/Repository/BiliUniverse/ADBlock
        git clone -b main https://github.com/BiliUniverse/ADBlock.git nhy_Tmp
        cp -r nhy_Tmp/* Tool-repo/Repository/BiliUniverse/ADBlock
        rm -rf nhy_Tmp
      # Wiki
    - name: Fork BiliUniverse Wiki
      run: |
        mkdir -p Tool-repo/Repository/BiliUniverse/Wiki
        git clone https://github.com/BiliUniverse/Universe.wiki.git erw_Tmp
        cp -r erw_Tmp/* Tool-repo/Repository/BiliUniverse/Wiki
        rm -rf erw_Tmp

      # Fork KOP-XIAO QX解析器
    - name: Fork KOP-XIAO 
      run: |
        mkdir -p Tool-repo/Repository/KOP-XIAO
        git clone -b master https://github.com/KOP-XIAO/QuantumultX.git ewr_Tmp
        cp -r ewr_Tmp/* Tool-repo/Repository/KOP-XIAO
        rm -rf ewr_Tmp

      # Fork chavyleung 定时任务
    - name: Fork chavyleung Task
      run: |
        mkdir -p Tool-repo/Repository/chavyleung
        git clone -b master https://github.com/chavyleung/scripts.git sdt_Tmp
        cp -r sdt_Tmp/* Tool-repo/Repository/chavyleung
        rm -rf sdt_Tmp

      # Fork Fokit 定时任务&脚本
    - name: Fork Fokit Task&Script
      run: |
        mkdir -p Tool-repo/Repository/Fokit
        git clone -b main https://github.com/FoKit/Scripts.git hyu_Tmp
        cp -r hyu_Tmp/* Tool-repo/Repository/Fokit
        rm -rf hyu_Tmp
      # 修改脚本链接
    - name: Edit Fokit/scripts
      run: |
        cd Tool-repo/Repository/Fokit/scripts
        for file in *.js; do
            if [ "$file" ] ; then
              # 修改脚本链接
              sed -i 's/raw\.githubusercontent\.com\/FoKit\/Scripts\/main\/scripts/raw.githubusercontent\.com\/ffddh\/Tool\/main\/Repository\/Fokit\/scripts/g' "$file"
            else
              echo "$file not found."
            fi
          done

      # Fork 墨鱼 重写规则
    - name: Fork ddgksf2013 Rewrite
      run: |
        mkdir -p Tool-repo/Repository/ddgksf2013/Rewrite
        git clone -b master https://github.com/ddgksf2013/Rewrite.git cds_Tmp
        cp -r cds_Tmp/* Tool-repo/Repository/ddgksf2013/Rewrite
        rm -rf cds_Tmp
   
      # Fork 墨鱼 脚本
    - name: Fork ddgksf2013 Script
      run: |
        mkdir -p Tool-repo/Repository/ddgksf2013/Scripts
        git clone -b master https://github.com/ddgksf2013/Scripts.git dcf_Tmp
        cp -r dcf_Tmp/* Tool-repo/Repository/ddgksf2013/Scripts
        rm -rf cdf_Tmp
      # 修改脚本链接
    - name: Edit ddgksf2013/Scripts
      run: |
        cd Tool-repo/Repository/ddgksf2013/Scripts
        for file in *.js; do
            if [ "$file" ] ; then
              # 修改脚本链接
              sed -i 's/github\.com\/ddgksf2013\/Scripts\/raw\/master/raw.githubusercontent\.com\/ffddh\/Tool\/main\/Repository\/ddgksf2013\/Scripts/g' "$file"
            else
              echo "$file not found."
            fi
          done
     
      # Fork 墨鱼 分流规则
    - name: Fork ddgksf2013 Filter
      run: |
        mkdir -p Tool-repo/Repository/ddgksf2013/Filter
        git clone -b master https://github.com/ddgksf2013/Filter.git ytu_Tmp
        cp -r ytu_Tmp/* Tool-repo/Repository/ddgksf2013/Filter
        rm -rf ytu_Tmp
    
      # Fork 墨鱼 代理规则
    - name: Fork ddgksf2013 Profile
      run: |
        mkdir -p Tool-repo/Repository/ddgksf2013/Profile
        git clone -b master https://github.com/ddgksf2013/Profile.git tyu_Tmp
        cp -r tyu_Tmp/* Tool-repo/Repository/ddgksf2013/Profile
        rm -rf tyu_Tmp
    
      # Fork 墨鱼 重写
    - name: Fork ddgksf2013 MoYu
      run: |
        mkdir -p Tool-repo/Repository/ddgksf2013/MOYU
        git clone -b master https://github.com/ddgksf2013/MoYu.git uyt_Tmp
        cp -r uyt_Tmp/* Tool-repo/Repository/ddgksf2013/MOYU
        rm -rf uyt_Tmp
      # 修改脚本链接
    - name: Edit ddgksf2013/MOYU
      run: |
        cd Tool-repo/Repository/ddgksf2013/MOYU
        for file in *.js; do
            if [ "$file" ] ; then
              # 修改脚本链接
              sed -i 's/github\.com\/ddgksf2013\/MoYu\/raw\/master/raw.githubusercontent\.com\/ffddh\/Tool\/main\/Repository\/ddgksf2013\/MOYU/g' "$file"
            else
              echo "$file not found."
            fi
          done

      # Fork evilbutcher 去广告&脚本
    - name: Fork evilbutcher Advertising&Script
      run: |
        mkdir -p Tool-repo/Repository/evilbutcher
        git clone -b main https://github.com/evilbutcher/QuantumultX.git dfr_Tmp
        cp -r dfr_Tmp/* Tool-repo/Repository/evilbutcher
        rm -rf dfr_Tmp

      # Fork blackmatrix7 分流规则
    - name: Fork blackmatrix7 filter
      run: |
        mkdir -p Tool-repo/Repository/blackmatrix7
        git clone -b master https://github.com/blackmatrix7/ios_rule_script.git xcv_Tmp
        cp -r xcv_Tmp/* Tool-repo/Repository/blackmatrix7
        rm -rf xcv_Tmp

      # fork 毒奶去广告
    - name: Fork limbopro Advertising
      run: |
        mkdir -p Tool-repo/Repository/limbopro
        git clone -b main https://github.com/limbopro/Adblock4limbo.git  cxv_Tmp
        cp -r cxv_Tmp/* Tool-repo/Repository/limbopro
        rm -rf cxv_Tmp

      # fork app2smile 去广告
    - name: Fork app2smile Advertising
      run: |
        mkdir -p Tool-repo/Repository/app2smile
        git clone -b master https://github.com/app2smile/rules.git  xvc_Tmp
        cp -r xvc_Tmp/* Tool-repo/Repository/app2smile
        rm -rf xvc_Tmp   

      # fork Repcz 分流规则
    - name: Fork Repcz filter
      run: |
        mkdir -p Tool-repo/Repository/Repcz
        git clone https://github.com/Repcz/Tool.git  edc_Tmp
        cp -r edc_Tmp/* Tool-repo/Repository/Repcz
        rm -rf edc_Tmp

      # fork Cats-Team 去广告规则
    - name: Fork Cats-Team Adblock
      run: |
        mkdir -p Tool-repo/Repository/Cats-Team
        git clone -b main https://github.com/Cats-Team/AdRules.git  dec_Tmp
        cp -r dec_Tmp/* Tool-repo/Repository/Cats-Team
        rm -rf dec_Tmp  
      #单独下载QX去广告规则
    - name: Download files to Cats-Team/Adblock
      run: |
        mkdir -p Tool-repo/Repository/Cats-Team/Adblock
        curl -L -o Tool-repo/Repository/Cats-Team/Adblock/ADRules.list "https://raw.githubusercontent.com/Cats-Team/AdRules/main/qx.conf"

     # fork Moli-X script
    - name: Fork Moli-X script
      run: |
        mkdir -p Tool-repo/Repository/Moli-X
        git clone -b main https://github.com/Moli-X/Resources.git  dce_Tmp
        cp -r dce_Tmp/* Tool-repo/Repository/Moli-X
        rm -rf dce_Tmp

     # fork Maasea script
    - name: Fork Maasea script
      run: |
        mkdir -p Tool-repo/Repository/Maasea
        git clone -b master https://github.com/Maasea/sgmodule.git  ecd_Tmp
        cp -r ecd_Tmp/* Tool-repo/Repository/Maasea
        rm -rf ecd_Tmp  

     # fork Keywos rule
    - name: Fork Keywos rule
      run: |
        mkdir -p Tool-repo/Repository/Keywos
        git clone -b main https://github.com/Keywos/rule.git  ecd_Tmp
        cp -r ecd_Tmp/* Tool-repo/Repository/Keywos
        rm -rf ecd_Tmp  

      # fork DualSubs YouTube字幕
    - name: Fork DualSubs YouTube
      run: |
        mkdir -p Tool-repo/Repository/DualSubs/YouTube
        git clone -b main https://github.com/DualSubs/YouTube.git  cxz_Tmp
        cp -r cxz_Tmp/* Tool-repo/Repository/DualSubs/YouTube
        rm -rf cxz_Tmp  
    - name: Fork DualSubs Universal
      run: |
        mkdir -p Tool-repo/Repository/DualSubs/Universal
        git clone -b main https://github.com/DualSubs/Universal.git  czx_Tmp
        cp -r czx_Tmp/* Tool-repo/Repository/DualSubs/Universal
        rm -rf czx_Tmp  
      # WiKi
    - name: Fork DualSubs WiKi
      run: |
        mkdir -p Tool-repo/Repository/DualSubs/WiKi
        git clone https://github.com/DualSubs/YouTube.wiki.git  zxc_Tmp
        cp -r zxc_Tmp/* Tool-repo/Repository/DualSubs/WiKi
        rm -rf zxc_Tmp 
    - name: Fork DualSubs WiKi
      run: |
        mkdir -p Tool-repo/Repository/DualSubs/WiKi
        git clone https://github.com/DualSubs/Universal.wiki.git  xzc_Tmp
        cp -r xzc_Tmp/* Tool-repo/Repository/DualSubs/WiKi
        rm -rf xzc_Tmp 
      # BoxJS
    - name: Fork DualSubs BoxJS
      run: |
        mkdir -p Tool-repo/Repository/DualSubs/BoxJS
        git clone -b main https://github.com/DualSubs/BoxJs.git  zcx_Tmp
        cp -r zcx_Tmp/* Tool-repo/Repository/DualSubs/BoxJS
        rm -rf zcx_Tmp 
  
      # fork githubdulong
    - name: Fork githubdulong Script
      run: |
        mkdir -p Tool-repo/Repository/githubdulong
        git clone -b master https://github.com/githubdulong/Script.git  kmi_Tmp
        cp -r kmi_Tmp/* Tool-repo/Repository/githubdulong
        rm -rf kmi_Tmp  


      # fork axtyet Tool
    - name: Fork axtyet Tool
      run: |
        mkdir -p Tool-repo/Repository/axtyet/Tool
        git clone -b main https://github.com/axtyet/Tool.git  mik_Tmp
        cp -r mik_Tmp/* Tool-repo/Repository/axtyet/Tool
        rm -rf mik_Tmp  


      # fork upscayl
    - name: Fork upscayl
      run: |
        mkdir -p Tool-repo/Repository/upscayl
        git clone -b main https://github.com/upscayl/upscayl.git  ikm_Tmp
        cp -r ikm_Tmp/* Tool-repo/Repository/upscayl
        rm -rf ikm_Tmp  
        

      # 保存、推送   
    - name: Add and Commits
      run: |
        cd Tool-repo
         if [[ -n $(git status -s) ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add --all
          git commit -m "$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')"
          git push origin HEAD
        else
          echo "No changes to commit."
        fi

    - name: Cleanup Workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 2
